In [2]:
class Person:
    def __init__(self, fname, lname):
        self.firstname = fname
        self.lastname = lname

    def printname(self):
        print(self.firstname, self.lastname)

#Use the Person class to create an object, and then execute the printname method:

x = Person("John", "Doe")
x.printname()


John Doe


In [7]:
class sq:
    def __init__(self,side):
        self.SIDE=side
        
    def getArea(self):
        return self.SIDE*self.SIDE
    
    def getPerimeter(self):
        return 4*self.SIDE

obj=sq(20)
print("the Area = ",obj.getArea())
print("the perimeter= ",obj.getPerimeter())

the Area =  400
the perimeter=  80


In [26]:
class factorial:
    def fact(self,n):
        self.factorial=1
        for i in range (1,n+1):
            self.factorial=i*self.factorial
        return self.factorial

obj=factorial()
num=int(input("Enter Number = "))
print("The Factorial ",num," is = ",obj.fact(num))

Enter Number = 6
The Factorial  6  is =  720


In [29]:
class addition:
      
    def add(self,p1,p2):
        return p1+p2
    
obj=addition()
num1=int(input("Enter Num1 = "))
num2=int(input("Enter Num2 = "))
print("The Sum Of ",num1," and ",num2," is = ",obj.add(num1,num2))

Enter Num1 = 1
Enter Num2 = 2
The Sum Of  1  and  2  is =  3


In [33]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [34]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [36]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [44]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [45]:
outData=np.arange(1,100,10)
print(outData)

[ 1 11 21 31 41 51 61 71 81 91]


In [53]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1[0])
print(a1,"\n")

print(a1[1:2],"\n")

[1 2 3]
[[1 2 3]
 [4 5 6]] 

[[4 5 6]] 



In [56]:
a1=np.random.normal(5,1,10)
print(a1,"\n")

print("Minimum values = ",np.min(a1))
print("Maximum values = ",np.max(a1))
print("Mean values    = ",np.mean(a1))
print("Median values  = ",np.median(a1))

[4.17095642 4.47470242 4.53764228 5.99367589 6.35787152 5.71368869
 4.61710058 5.3916811  5.48527694 3.76725004] 

Minimum values =  3.7672500443397015
Maximum values =  6.35787151882732
Mean values    =  5.050984589022661
Median values  =  5.0043908392850796


In [57]:
a1=np.array([(1,2),(3,4)])
a2=np.array([(1,2),(3,4)])
np.dot(a1,a2)

array([[ 7, 10],
       [15, 22]])

In [3]:
import pandas as pd
dict={
    "Name":["Uma","Heckle","Pilocia"],
     "Ph No":["100","200","300"],
     "Address":["H","H","H"]
}

b=pd.DataFrame(dict)
b.index=["1","2","3"]
print(b)

      Name Ph No Address
1      Uma   100       H
2   Heckle   200       H
3  Pilocia   300       H


In [23]:
test_str = "213456111"
  
all_freq = {} 
  
for i in test_str: 
    if i in all_freq: 
        all_freq[i] += 1
    else: 
        all_freq[i] = 1
  
# printing result  
print ("Count of all characters in",test_str," is :\n "+  str(all_freq)) 


Count of all characters in 213456111  is :
 {'2': 1, '1': 4, '3': 1, '4': 1, '5': 1, '6': 1}


In [13]:
def check(s1, s2): 
      
    # the sorted strings are checked  
    if(sorted(s1)== sorted(s2)): 
        print("The strings are anagrams.")  
    else: 
        print("The strings aren't anagrams.")          
          
# driver code   
s1 ="listen"
s2 ="silent" 
check(s1, s2) 

The strings are anagrams.


In [1]:
string = input("Enter a string = ")

Digits=['0','1','2','3','4','5','6','7','8','9']

for i in range(10): 
    print("{} Times Repeated {}".format(i,string.count(Digits[i])))

Enter a string = 213abc
0 Times Repeated 0
1 Times Repeated 1
2 Times Repeated 1
3 Times Repeated 1
4 Times Repeated 0
5 Times Repeated 0
6 Times Repeated 0
7 Times Repeated 0
8 Times Repeated 0
9 Times Repeated 0
